version: "3"

services:
  entry:
    cpuset: "7"
    container_name: mat_entry
    build: "./Entry"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 0.5G
  bogo:
    cpuset: "8"
    build: "./Bogo"
    container_name: mat_bogo
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 0.5G
  bubble:
    cpuset: "9"
    build: "./Bubble"
    container_name: mat_bubble
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 0.5G
  writereaddelete:
    cpuset: "10"
    build: "./WriteReadDelete"
    container_name: mat_write
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 0.5G         
